mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

mysite/polls/urls.py
from django.urls import path 
from . import views

app_name = 'polls'

urlpatterns = [
        # path('', views.index, name='index'),
        path('', views.Index.as_view(), name='index'),
        # path('<int:question_id>/', views.detail, name='detail'),
        path('<int:pk>/', views.Detail.as_view(), name='detail'),
        # # path('<int:question_id>/results/', views.results, name='results'),
        path('<int:pk>/results/', views.Results.as_view(), name='results'),
        path('<int:question_id>/vote/', views.vote, name='vote'),
        path('createquestion/', views.CreateQuestion.as_view(), name='create_question'),
        path('deletequestion/<int:pk>/', views.DeleteQuestion.as_view(), name='delete_question'),
        #path('<int:pk>/createchoice/', views.Vote.as_view(), name='vote'),
        #path('<int:pk>/updatechoice/'),
        #path('<int:pk>/deletechoice/'),
]

mysite/polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.urls import reverse
# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


    def __str__(self):
        return self.question_text


    def was_pubished_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
    def get_absolute_url(self):
        return reverse('polls:detail', kwargs={'pk': self.pk})


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length = 200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse, reverse_lazy 
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.utils import timezone
# Create your views here.


class Index(ListView):
    template_name = 'polls\index.html'
    context_object_name = 'latest_question_list' 

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = 'polls\index.html'
#     context = {
#         'latest_question_list':latest_question_list,
#     }
#     return render(request, template, context)


class Detail(DetailView):
    model = Question
    template_name = 'polls/detail.html'
    context_object_name = 'question'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['choice'] = Choice.objects.all()
        return context 

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     template = 'polls/detail.html'
#     context = {'question':question}
#     return render(request, template, context) 

class Results(DetailView):
    model = Question
    template_name = 'polls/result.html'
    context_object_name = 'question'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['choice'] = Choice.objects.all()
        return context 


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     template = 'polls/result.html'
#     context = {'question':question}
#     return render(request, template, context)


class CreateQuestion(CreateView):
    model = Question
    fields = ['question_text']

    
    def form_valid(self, form):
        form.instance.pub_date = timezone.now()
        return super().form_valid(form)


class DeleteQuestion(DeleteView):
    model = Question
    success_url = reverse_lazy('polls:index')

# class CreateChoice(CreateView):
    
#     def get_object(self):



def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/templates/polls/detail.html
<!DOCTYPE <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Page Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>
<body>
    <h1>{{ question.question_text }}</h1>
   {% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
   
   <form action = "{% url 'polls:vote' question.id %}" method="post">
       {% csrf_token %}
       {% for choice in question.choice_set.all %}
        <input type ="radio" 
               name="choice" 
               id="choice{{ forloop.counter }}" 
               value="{{ choice.id }}"/>
        <label for="choice{{ forloop.counter }}">{{choice.choice_text}}</label><br/>
        {% endfor %}
        <input type="submit" value="Vote"/>
   </form>
   <form method="POST" action="{% url 'polls:delete_question' question.id %}">
    {% csrf_token %}<input type="submit" class="btn btn-danger" value="DELETE">
    </form>
    <ul>

    </ul>
</body>
</html>

mysite/polls/templates/polls/index.html
<!DOCTYPE <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Page Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>
<body>
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>no polls available</p>
    {% endif %}
    <a href="{% url 'polls:create_question' %}" type="button" class="btn btn-primary">Create New </a>
</body>
</html>

mysite/polls/templates/polls/question_form.html
<!DOCTYPE <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Create Question</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>
<body>
    <h1>
        {% if not form.instance.pk %}
        Ask New Question
        {% endif %}
    </h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
</body>
</html>

mysite/polls/templates/polls/result.html
<!DOCTYPE <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Page Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}: {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>